<?xml version="1.0" encoding="UTF-8"?>
<dict>
	<key>fileTypes</key>
	<array>
		<string>delta</string>
	</array>
	<key>name</key>
	<string>Delta</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.delta</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.delta</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.delta</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\\\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>string-interpolation</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delta</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\+</string>
							<key>name</key>
							<string>keyword.operator.delta</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>,</string>
			<key>name</key>
			<string>comment.punctuation.comma.delta</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[A-Z][A-Za-z]+\b</string>
			<key>name</key>
			<string>string.class.delta</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(class|deinit|enum|func|import|init|undefined|let|struct|typealias|var|break|case|continue|do|else|if|in|for|return|switch|while|mutating|mutable|null)\b</string>
			<key>name</key>
			<string>keyword.reserved.delta</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>string.boolean.delta</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(int|uint|bool|int64|uint64|float)\b</string>
			<key>name</key>
			<string>string.dtype.delta</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(-|\.)?\b[0-9]+(\.[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.delta</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|\*|/|%|=|!|\^|~|\||\?|&lt;|&gt;|&amp;</string>
			<key>name</key>
			<string>keyword.operator.delta</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+(?=\s*:)</string>
			<key>name</key>
			<string>meta.tag.delta</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\.)\w+(?=\.|\s|,|;|\)|\?|\+|\-|=)</string>
			<key>name</key>
			<string>support.constant.delta</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+(?=\s*\()</string>
			<key>name</key>
			<string>support.function.delta</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.delta</string>
</dict>
</plist>